permalink: /:title/
plugins:
  - jekyll-sitemap

title: sebbas.org
url: https://sebbas.org
baseurl: ""
description: "Personal website of Sebastián Barschkis. Fluid simulation developer for Blender 3D."
author: Sebastian Barschkis
stackoverflow: 1480784/sebbas
youtube: UCiU3oTGKL4GDr5xgK_EMjnQ
ircchannel: blendercoders # a channel that you are frequenting
username: sebbas
email: sebbas@sebbas.org
profile_photo_1: "https://dl.dropboxusercontent.com/s/aozc1kylygtxjbc/profile_sebbas_01.jpg"
profile_photo_2: "https://dl.dropboxusercontent.com/scl/fi/zrhdli99eqc8p6zy4bgy6/profile_sebbas_02.png?rlkey=ylysghxq3gsoczeajysqia6td&dl=0"
profile_photo_3: "https://dl.dropboxusercontent.com/scl/fi/l8pd91hva5shjh1mnt5v1/profile_sebbas_03.jpg?rlkey=0xsbrfw3g6a0llw2kf0azmoj9&st=s2p5hdxk&dl=0"

timezone: Europe/Madrid
google_analytics_tracking_id: G-JQLMSGRCYJ
