permalink: /:title/
plugins:
  - jekyll-sitemap

title: sebbas.org
url: https://sebbas.org
baseurl: ""
description: "Personal website of Sebastián Barschkis. Fluid simulation developer for Blender 3D."
author: Sebastián Barschkis
stackoverflow: 1480784/sebbas
youtube: UCiU3oTGKL4GDr5xgK_EMjnQ
ircchannel: blendercoders # a channel that you are frequenting
username: sebbas
email: sebbas ( at ) sebbas.org

timezone: Europe/Madrid
google_analytics_tracking_id: G-JQLMSGRCYJ
